name: ML Service CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies and test in machine-learning-client
      run: |
        python -m pip install --upgrade pip
        pip install -r machine-learning-client/requirements.txt
        pip install pytest
        cd machine-learning-client
        pytest

    - name: Build Docker image
      run: |
        cd machine-learning-client
        docker build . --file Dockerfile