name: ML Service CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Change to ML directory
      run: |
          cd machine-learning-client
          python -m pip install --upgrade pip
          pip install -r requirements.txt

    - name: Test with pytest
      run: |
        cd machine-learning-client
        pip install pytest
        pytest

    - name: Build Docker image
      run: |
        cd machine-learning-client
        docker build . --file Dockerfile
